### ISSUE TITLE
seems to be throwing a bunch of errors

### ISSUE THREAD

**Issue by boppii** [fayaz12g/totk-aar#1]
maybe i have python installed wrong? 
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1948, in __call__
  File "GUI.py", line 87, in select_output_folder
NameError: name 'status_label' is not defined
Downloading zip file
Extracting zip file
Traceback (most recent call last):
  File "C:\Users\bopbd\AppData\Local\Temp\_MEI111642\download.py", line 64, in <module>
    download_extract_copy(controller_id, output_folder)
  File "C:\Users\bopbd\AppData\Local\Temp\_MEI111642\download.py", line 34, in download_extract_copy
    with zipfile.ZipFile(zip_file_path, "r") as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bopbd\AppData\Local\Programs\Python\Python311\Lib\zipfile.py", line 1299, in __init__
    self._RealGetContents()
  File "C:\Users\bopbd\AppData\Local\Programs\Python\Python311\Lib\zipfile.py", line 1366, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
0070201E
0070201E
Patch file created: F:/TOK mods\AAR MOD\exefs\main-1.0.0.pchtxt
0070201E
0070201E
Patch file created: F:/TOK mods\AAR MOD\exefs\main-1.1.0.pchtxt
0070201E
0070201E
Patch file created: F:/TOK mods\AAR MOD\exefs\main-1.1.1.pchtxt
0070201E
0070201E
Patch file created: F:/TOK mods\AAR MOD\exefs\main-1.1.2.pchtxt
Input file not found.
Invalid BLARC file path.
Centered HUD value is set to  False
The scaling factor is  0.7441860465116279
Traceback (most recent call last):
  File "C:\Users\bopbd\AppData\Local\Temp\_MEI111642\script.py", line 21, in <module>
    file_names = os.listdir(blyt_folder)
                 ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'F:/TOK mods\\AAR MOD\\temp\\Common.Product.110.Nin_NX_NVN\\blyt'
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1948, in __call__
  File "GUI.py", line 136, in create_patch
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'F:/TOK mods\\AAR MOD\\temp\\Common.Product.110.Nin_NX_NVN.blarc'
```

**Comment by boppii** [comment]
had to update pip oops
