### ISSUE TITLE
ImportError, FileNotFoundError

### ISSUE THREAD

**Issue by jfelver** [fayaz12g/totk-aar#4]
I'm getting a few errors when attempting to run the code using a 21:9, Xbox, Colored, Western, Center selection.

Edit: Python 3.8.0 is the globally installed version

The console log looks like the following:

```
Traceback (most recent call last):
  File "E:\Program Files\Yuzu\yuzu\user\load\0100F2C0115B6000\AAR 2.1.1\download.py", line 4, in <module>
    import requests
  File "E:\Program Files\Yuzu\yuzu\user\load\0100F2C0115B6000\AAR 2.1.1\requests\__init__.py", line 43, in <module>
    import urllib3
  File "E:\Program Files\Yuzu\yuzu\user\load\0100F2C0115B6000\AAR 2.1.1\urllib3\__init__.py", line 13, in <module>
    from . import exceptions
  File "E:\Program Files\Yuzu\yuzu\user\load\0100F2C0115B6000\AAR 2.1.1\urllib3\exceptions.py", line 3, in <module>
    import socket
  File "E:\Program Files\Python\lib\socket.py", line 49, in <module>
    import _socket
ImportError: Module use of python311.dll conflicts with this version of Python.
Keystone Engine not found. Installing...
Keystone Engine is already installed.
Failed to install Keystone Engine. Please install it manually.
Installing zstandard library...
Failed to install zstandard library. Please install it manually.
Invalid BLARC file path.
Centered HUD value is set to  True
The scaling factor is  0.7619047619047619
Traceback (most recent call last):
  File "E:\Program Files\Yuzu\yuzu\user\load\0100F2C0115B6000\AAR 2.1.1\script.py", line 21, in <module>
    file_names = os.listdir(blyt_folder)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'E:/Program Files/Yuzu/yuzu/user/load/0100F2C0115B6000\\AAR MOD\\temp\\Common.Product.110.Nin_NX_NVN\\blyt'
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1948, in __call__
  File "GUI.py", line 139, in create_patch
    os.remove(blarc_file_path)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'E:/Program Files/Yuzu/yuzu/user/load/0100F2C0115B6000\\AAR MOD\\temp\\Common.Product.110.Nin_NX_NVN.blarc'
```

**Comment by jfelver** [comment]
Update:

Downloaded Python 3.11.3 and ran from source - it seems to now be working fine.

**Comment by fayaz12g** [comment]
Fixed by using Python 3.11, as stated in "ImportError: Module use of python311.dll conflicts with this version of Python.". Thank you!

**Comment by JasonYCao** [comment]
I'm not sure how to apply this fix, can someone elaborate?

**Comment by fayaz12g** [comment]
> I'm not sure how to apply this fix, can someone elaborate?

If you use a version above 4.0.0 it will work without the python dependency
